apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::719256692338:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-DDEFH1VUUEVW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::719256692338:role/UdacityFlaskDeployCBKubectlRole
      username: build

kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-25T22:35:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1766"
  uid: 6b1e3d5b-041a-4692-b5f3-d07543682b92
